### ISSUE TITLE
Unify distribution Sanbox with nette/sandbox

### ISSUE THREAD

**Issue by vojtech-dobes** [nette/build-tools#9]
Currently the Sandbox in distribution package contains whole Nette in libs/Nette directory. On the other hand, nette/sandbox expects Composer to install Nette into libs/nette/nette directory. This should be unified to the latter way (libs/nette/nette).

Presence of Nette in libs/Nette causes trouble after `composer install` command.

**Comment by milo** [comment]
Sandbox in distribution ZIP package is a composer project. This can be closed.
